import type { Locale } from "@/lib/i18n-data";

const messages: Record<Locale, Record<string, string>> = {
  en: {},
  es: { Tuner: "Radio", Search: "Buscar", Discover: "Descubrir", Favorites: "Favoritos", History: "Historial", About: "Acerca de", FAQ: "Preguntas frecuentes", "Skip to content": "Saltar al contenido", "What's the mood?": "¿Qué ambiente buscas?", Feel: "Ambiente", "Travel by radio": "Viaja con la radio", Places: "Lugares", "All countries": "Todos los países", "On air now": "En directo", "Most played worldwide": "Más escuchadas en el mundo", "Search stations": "Buscar emisoras", "Scan the dial": "Explora el dial", "Find live radio by name, country, language or genre.": "Encuentra radio en directo por nombre, país, idioma o género.", Country: "País", Language: "Idioma", "All languages": "Todos los idiomas", "Genre or tag": "Género o etiqueta", "Sort by": "Ordenar por", "Most played": "Más escuchadas", "Most voted": "Más votadas", Name: "Nombre", Random: "Aleatorio", "Search station names": "Buscar emisoras", "Your presets": "Tus emisoras", "Saved on this device only. No account needed.": "Guardadas solo en este dispositivo. No necesitas una cuenta.", "Recently played": "Escuchadas recientemente", Logbook: "Historial", "Your last 50 stations. Stored on this device only.": "Tus últimas 50 emisoras. Guardadas solo en este dispositivo.", "Language preference": "Idioma de la interfaz" },
  fr: { Tuner: "Radio", Search: "Rechercher", Discover: "Découvrir", Favorites: "Favoris", History: "Historique", About: "À propos", FAQ: "FAQ", "Skip to content": "Aller au contenu", "What's the mood?": "Quelle ambiance ?", Feel: "Ambiance", "Travel by radio": "Voyagez par la radio", Places: "Lieux", "All countries": "Tous les pays", "On air now": "En direct", "Most played worldwide": "Les plus écoutées dans le monde", "Search stations": "Rechercher des radios", "Scan the dial": "Parcourir les fréquences", "Find live radio by name, country, language or genre.": "Trouvez des radios en direct par nom, pays, langue ou genre.", Country: "Pays", Language: "Langue", "All languages": "Toutes les langues", "Genre or tag": "Genre ou étiquette", "Sort by": "Trier par", "Most played": "Les plus écoutées", "Most voted": "Les mieux notées", Name: "Nom", Random: "Aléatoire", "Search station names": "Rechercher une station", "Your presets": "Vos favoris", "Saved on this device only. No account needed.": "Enregistrés sur cet appareil. Aucun compte requis.", "Recently played": "Écoutées récemment", Logbook: "Journal", "Your last 50 stations. Stored on this device only.": "Vos 50 dernières stations, enregistrées sur cet appareil.", "Language preference": "Langue de l’interface" },
  ar: { Tuner: "الراديو", Search: "بحث", Discover: "اكتشف", Favorites: "المفضلة", History: "السجل", About: "حول", FAQ: "الأسئلة الشائعة", "Skip to content": "انتقل إلى المحتوى", "What's the mood?": "ما هو مزاجك؟", Feel: "أجواء", "Travel by radio": "سافر عبر الراديو", Places: "أماكن", "All countries": "كل البلدان", "On air now": "يبث الآن", "Most played worldwide": "الأكثر استماعًا حول العالم", "Search stations": "ابحث عن المحطات", "Scan the dial": "تصفح المحطات", "Find live radio by name, country, language or genre.": "اعثر على إذاعات مباشرة حسب الاسم أو البلد أو اللغة أو النوع.", Country: "البلد", Language: "اللغة", "All languages": "كل اللغات", "Genre or tag": "النوع أو الوسم", "Sort by": "ترتيب حسب", "Most played": "الأكثر استماعًا", "Most voted": "الأعلى تصويتًا", Name: "الاسم", Random: "عشوائي", "Search station names": "ابحث عن أسماء المحطات", "Your presets": "محطاتك المحفوظة", "Saved on this device only. No account needed.": "محفوظة على هذا الجهاز فقط. لا حاجة إلى حساب.", "Recently played": "استُمعت مؤخرًا", Logbook: "السجل", "Your last 50 stations. Stored on this device only.": "آخر 50 محطة استمعت إليها، محفوظة على هذا الجهاز.", "Language preference": "لغة الواجهة" },
  pt: { Tuner: "Rádio", Search: "Pesquisar", Discover: "Descobrir", Favorites: "Favoritos", History: "Histórico", About: "Sobre", FAQ: "Perguntas frequentes", "Skip to content": "Ir para o conteúdo", "What's the mood?": "Qual é o clima?", Feel: "Clima", "Travel by radio": "Viaje pelo rádio", Places: "Lugares", "All countries": "Todos os países", "On air now": "No ar", "Most played worldwide": "Mais ouvidas no mundo", "Search stations": "Pesquisar estações", "Scan the dial": "Explore o dial", "Find live radio by name, country, language or genre.": "Encontre rádios ao vivo por nome, país, idioma ou gênero.", Country: "País", Language: "Idioma", "All languages": "Todos os idiomas", "Genre or tag": "Gênero ou tag", "Sort by": "Ordenar por", "Most played": "Mais ouvidas", "Most voted": "Mais votadas", Name: "Nome", Random: "Aleatório", "Search station names": "Pesquisar estações", "Your presets": "Suas favoritas", "Saved on this device only. No account needed.": "Salvas apenas neste dispositivo. Sem necessidade de conta.", "Recently played": "Ouvidas recentemente", Logbook: "Histórico", "Your last 50 stations. Stored on this device only.": "Suas últimas 50 estações, salvas neste dispositivo.", "Language preference": "Idioma da interface" },
};

export function t(locale: Locale, text: string): string {
  return messages[locale][text] ?? text;
}
